name: profile_ui


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  json_annotation: ^4.3.0
  fl_chart: ^0.50.1
  core:
    path: ../../../core
  ui_kit:
    path: ../../../ui_kit
  profile_data:
    path: ../data

  cupertino_icons: ^1.0.2

dev_dependencies:
  freezed: ^1.1.1
  build_runner: ^2.1.5
  json_serializable: ^6.0.1
  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true



