name: totalfit
description: Totalfit mobile app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.21+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  flutter_picker:
    git: https://github.com/yangyxd/flutter_picker.git
  flutter_facebook_auth: ^3.5.6+3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  flutter_switch: ^0.3.2
  video_player: 2.3.0
  chewie: 1.3.1
  throttling: ^1.0.0
  package_info_plus: ^1.0.4
  device_info: ^2.0.2
  app_tracking_transparency: 2.0.2+1
  google_sign_in: 5.0.2
  sign_in_with_apple: 3.0.0
  sqflite: any
  transparent_image: <2.0.0
  shared_preferences: ^2.0.11
  flutter_redux: 0.8.2
  redux_epics: 0.15.1
  flutter_cupertino_localizations: ^1.0.1
  app_settings: 4.0.4
  flutter_cupertino_date_picker: 1.0.23+1
  shimmer: ^2.0.0
  flutter_emoji: 2.2.1+1
  flutter_blurhash: 0.6.0
  image_size_getter: 0.1.1
  flutter_staggered_grid_view: 0.3.0
  image_picker: 0.7.2+1
  wakelock: ^0.6.1+2
  flutter_hooks: 0.11.0
  syncfusion_flutter_sliders: ^19.2.46
  sembast: 2.4.7+4
  simple_tooltip: 0.1.12
  cached_network_image: ^3.1.0+1
  url_launcher: ^6.0.17
  firebase_core: 1.10.0
  firebase_analytics: 8.1.1
  flutter_native_timezone: 2.0.0
  flutter_keyboard_visibility: ^5.2.0
  infinite_scroll_pagination: ^2.3.0
  uni_links: 0.4.0
  amplitude_flutter: 2.2.3
  image: 3.0.2
  mockito: 5.0.7
  animations: ^1.1.2
  dots_indicator: ^1.2.0
  flutter_spinkit: 4.1.2+1
  flutter_bloc: 7.2.0
  confetti: 0.5.5
  flutter_local_notifications: 5.0.0+1
  flutter_svg: ^1.0.3
  purchases_flutter: ^3.10.0
  equatable: ^2.0.2
  rive: ^0.7.10
  animated_item_picker: ^1.0.4
  firebase_messaging: 10.0.2
  adjust_sdk: ^4.29.1
  facebook_app_events: <=0.14.7
  navigation_history_observer: ^1.1.0
  sentry_flutter: ^6.4.0
  core:
    path: core
  workout_data_legacy:
    path: feature/workout/data_legacy
  workout_api:
    path: feature/workout/api
  mood_api:
    path: feature/mood/api
  ui_kit:
    path: ui_kit
  impl:
    path: feature/workout/impl
  workout_data:
    path: feature/workout/data
  workout_use_case:
    path: feature/workout/use_case
  force_upgrade_service:
    path: feature/force_upgrade/service
  profile_api:
    path: feature/profile/api


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
    - family: BottomNavBarIcon
      fonts:
        - asset: assets/fonts/BottomNavBarIcon.ttf
    - family: OnboardingIcons
      fonts:
        - asset: assets/fonts/OnboardingIcons.ttf
    - family: Social_icons
      fonts:
        - asset: assets/fonts/Social_icons.ttf
    - family: HexagonIcons
      fonts:
        - asset: assets/fonts/HexagonIcons.ttf
    - family: PlaybackIcons
      fonts:
        - asset: assets/fonts/PlaybackIcons.ttf
    - family: ArrowIcon
      fonts:
        - asset: assets/fonts/ArrowIcon.ttf
    - family: Triangle
      fonts:
        - asset: assets/fonts/Triangle.ttf
    - family: Emotion
      fonts:
        - asset: assets/fonts/Emotion.ttf
    - family: Sound
      fonts:
        - asset: assets/fonts/Sound.ttf
    - family: CloudIcon
      fonts:
        - asset: assets/fonts/CloudIcon.ttf
    - family: ProgramInfoIcons
      fonts:
        - asset: assets/fonts/ProgramInfoIcons.ttf
    - family: ProgrammsIcon2
      fonts:
        - asset: assets/fonts/ProgrammsIcon2.ttf
    - family: PTSerif-Regular
      fonts:
        - asset: assets/fonts/PTSerif-Regular.ttf
  assets:
    - assets/sounds/voice_message/
    - assets/sounds/
    - assets/images/
    - assets/icons/
    - assets/rive/
    - assets/
    - config/

flutter_intl:
  enabled: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/ic_launcher.png"
