name: workout_api
version: 1.0.1

publish_to: none


environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  workout_data_legacy:
    path: ../../../feature/workout/data_legacy
  core:
    path: ../../../core
  impl:
    path: ../../../feature/workout/impl
  workout_ui:
    path: ../ui
  workout_data:
    path: ../data
  workout_use_case:
    path: ../use_case

dev_dependencies:
  build_runner: ^2.1.5


