name: workout_use_case
version: 1.0.1

publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:

  json_annotation: ^4.4.0

  workout_data:
    path: ../data
  core:
    path: ../../../core

dev_dependencies:
  build_runner: ^2.1.5
  json_serializable: ^6.0.1

