name: force_upgrade_service

version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  package_info_plus: ^1.0.4
  xml: ^5.0.2
  html: ^0.15.0
  version: ^2.0.0
  force_upgrade_data:
    path: ../data
  ui:
    path: ../ui
  core:
    path: ../../../core


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
