name: impl
version: 1.0.1

publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  path_provider: 2.0.1
  http: ^0.13.0
  core:
    path: ../../../core
  workout_api:
    path: ../../../feature/workout/api
  workout_data:
    path: ../../../feature/workout/data
  workout_data_legacy:
    path: ../../../feature/workout/data_legacy
  workout_use_case:
    path: ../../../feature/workout/use_case

dev_dependencies:
  build_runner: ^2.1.5


